### PR TITLE
FRW-390 Added usage of new ruleset filepath and fallback to legacy

### LINKED ISSUE #54: Error on required ruleset.xml which isn't present
https://github.com/spryker/git-hook/blob/efad48ab3458bfdd0d0e3e21c8ecd722d142bbbd/src/GitHook/Command/FileCommand/PreCommit/CodeStyleFixCommand.php#L45

The requirement for the config/ruleset.xml causes an error:  ```ERROR: the "config/ruleset.xml" coding standard is not installed.```

EDIT:
Replacing the mentioned file path with ```--standard=phpcs.xml``` solved the issue without further errors.

### PR DESCRIPTION
**Pull request by yaroslav-spryker**
Resolves https://github.com/spryker/git-hook/issues/54

### CODE REVIEW

**Review by olhalivitchuk — APPROVED** [review]

**Review by geega — APPROVED** [review]

File: src/GitHook/Command/FileCommand/PreCommit/CodeStyleFixCommand.php [hunk 1]
```diff
@@ -42,10 +62,28 @@ public function run(CommandContextInterface $context): CommandResultInterface
...
+     * @return string
+     */
+    protected function getStandardRulesetOption(): string
+    {
+        $filepath = static::RULESET_LEGACY_PATH;
+        if (file_exists(PROJECT_ROOT . DIRECTORY_SEPARATOR . static::RULESET_PATH)) {
+            $filepath = static::RULESET_PATH;
+        }
+
+        return sprintf('%s=%s', static::OPTION_STANDARD, $filepath);
```
Comment (dereuromark) [inline src/GitHook/Command/FileCommand/PreCommit/CodeStyleFixCommand.php]: Please check the Jira ticket

If the root file exists, no --standard must be added here at all

Comment (dereuromark) [reply src/GitHook/Command/FileCommand/PreCommit/CodeStyleFixCommand.php]: Also, if the config/ one doesnt exist it shouldnt error with that legacy path, but instead a meaningful message should clarify to add root file instead.

**Review by dereuromark — APPROVED** [review]
